django-portfolio/blog/urls.py
from django.urls import path 
from .views import render_posts, post_detail

app_name = 'blog'

urlpatterns = [
    path('', render_posts, name='posts'), # now, if we go to /blog/ we will render this
    path('<int:post_id>', post_detail, name="post_detail"), # using a dynamic url to show details of every post. For example: blog/12
]

django-portfolio/django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include # include allows us to call other urls from other apps
# basically with this imports below makes possible to show images in the frontend
from django.conf.urls.static import static 
from django.conf import settings 
from portfolio import views # import the views from portfolio app to be able to show the views :v 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name = 'home'),
    path('blog/', include('blog.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # and also this


# to create a new user/admin use: 
# python manage.py createsuperuser 

django-portfolio/blog/models.py
from django.db import models
from django.db.models.fields import CharField, URLField, TextField, DateField
from django.db.models.fields.files import ImageField 
import datetime 
# we import the fields, URLField is basically a charfield for a URL


class Post(models.Model):
    title = CharField(max_length=100)
    description = TextField()
    image = ImageField(upload_to='blog/images') # basically this is going to create a folder inside media with name 'blog'  
    date = DateField(datetime.date.today)
    tags = CharField(max_length=150)
    
     

django-portfolio/portfolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField # we import the fields, URLField is basically a charfield for a URL
from django.db.models.fields.files import ImageField # we're going to save images as well

# define what I want to save in the database, the model
# ctrl + space 

class Project (models.Model): # always use 'model.Model' 
    title = CharField(max_length=100) 
    description = CharField(max_length=250)
    image = ImageField(upload_to = 'portfolio/images/') # inside portfolio app there will be a folder where the images will be stored
    url = URLField(blank=True) 
    tags = CharField(max_length=150)
    

django-portfolio/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

def render_posts(request): # this is going to render the post html
    posts = Post.objects.all()    
    
    return render(request, 'posts.html', {'posts' : posts})

def post_detail(request, post_id): 
    post = get_object_or_404(Post,pk=post_id) # is going to search inside db.sqlite3, in case it exists we return something 
    return render(request, 'post_detail.html', {'post' : post } ) # and we send it to our post_detail.html
    

django-portfolio/portfolio/views.py
from django.shortcuts import render
from .models import Project # from this models.py we import the model Project cause we want to make a query and get all the projects to show in home.html

# we're going to show all the projects in this view
def home(request): 
    projects = Project.objects.all() # to be able to use this data in the html, we use a dictionary and we proceed 
    
    return render(request, 'home.html', {'projects': projects}) 

django-portfolio/blog/templates/post_detail.html
{% extends 'layout.html' %}

{% block content %}

<div class="text-center">

  <h1>{{post.title}}</h1>
  <h2 class="my-2 h5 text-muted">{{post.date}}</h2>

  <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid">

  <div class="my-4">

  {{post.description}}
  </div>
</div>

{% endblock %}

django-portfolio/blog/templates/posts.html
{% extends 'layout.html' %}

{% block content %}

<h1 class="fs-2">Posts</h1>
<h3>There are {{total_posts}} post{{total_posts|pluralize}}</h3>

{% for post in posts %}

<div class="py-3">

  <div class="card card-body bg-black">
    <div class="row">

      <div class="col-3">
        <img class="img-fluid" src="{{post.image.url}}" alt="{{post.title}}">

      </div>
      <div class="col-9">

        <h1>{{post.title}}</h1>
        <p>{{post.description|striptags|truncatechars:100}}</p>
        <p>{{post.date|date:'M d Y'|upper}}</p>

        <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-light rounded-0 btn-sm" target="__blank"
         rel="noreferrer">{{post.title}}</a>
      </div>
    </div>
  </div>
</div>

{% endfor %}

{% endblock %}

django-portfolio/portfolio/templates/home.html
{% extends 'layout.html' %}
{% block content %}

{% load static %}

<header class="row bg-black" >
    <div class="col-md-4">
        <img src="{% static 'portfolio/leoPortfolio.png' %}" style= "width: 100%; height: 100%"alt="leoPortfolio">
    </div>
    <div class="col-md-8 my-auto">
        <h1>Hi! I am Leonardo </h1>
        <h3>I like to build things </h3>
    </div>
</header>


<div class="row my-4 text-center">

    <h3>My Projects</h3>
  
    {% for project in projects %}
    <div class="col-md-4 p-4">
      <div class="card bg-black card-project">
        <img src="{{project.image.url }}" class="card-img-top" />
  
        <div class="card-body">
  
          <h2>{{ project.title }}</h2>
          <p>{{ project.description }}</p>
          <p>Tags: {{ project.tags }} </p>
  
          {% if project.url %}
          <a href="{{project.url}}" class="btn btn-light rounded-0 btn-sm" target="__blank" rel="noreferrer">Visit the
            Project</a>
          {% endif %}
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  
  
  {% endblock %}

django-portfolio/portfolio/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Django Porfolio</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>

<body class="text-light">

  {% include 'partials/navbar.html' %}

  <div class="container p-4">
    {% block content %}
    {% endblock %}
  </div>

</body>

</html>

django-portfolio/portfolio/templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-black">
  <div class="container">
    <a class="navbar-brand fw-bold fst-italic" href="/">EST4Life</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:posts' %}">Blog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="https://www.youtube.com/watch?v=dQw4w9WgXcQ">Extra</a>
        </li>
      </ul>
    </div>
  </div>
</nav>